language: php
php:
  - '7.0'
before_install:
  - composer require phpunit/phpunit:5.2.* satooshi/php-coveralls:1.0.*
  - composer install
script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
after_script:
- php vendor/bin/coveralls -v


